<#
.SYNOPSIS
    Generate the dependency-update documentation pages from a Bump-Deps.ps1 report.

.DESCRIPTION
    Reads the JSON report produced by scripts/Bump-Deps.ps1 (-RecordsPath) and
    prepends a dated entry to the bilingual dependency log:

      docs/Dependencies/index.md      (PL)
      docs-en/Dependencies/index.md   (EN)

    Each entry lists — per *.csproj — which PackageReference moved from which
    version to which version, plus the packages that were deliberately skipped
    (license drift, ignore-list ceiling, undeclared license).

    Only the region between the <!-- BUMP-LOG:START --> and <!-- BUMP-LOG:END -->
    markers is rewritten; everything above and below is preserved. Pages are
    created from a template when missing. The most recent -MaxEntries entries
    are kept so the pages do not grow without bound.

    This is what keeps the automated bump PR green: the "Docs guard" workflow
    rejects a PR that touches src/ without touching docs/ + docs-en/.

.PARAMETER RecordsPath
    Path to the JSON report written by Bump-Deps.ps1 -RecordsPath.

.PARAMETER Path
    Repository root. Defaults to the current directory.

.PARAMETER Date
    Entry date (yyyy-MM-dd). Defaults to the report's generation date (UTC).

.PARAMETER MaxEntries
    How many dated entries to keep on each page. Defaults to 24.

.PARAMETER RunUrl
    Optional link to the workflow run that produced the bump.

.EXAMPLE
    ./scripts/Bump-Deps.ps1 -DryRun -RecordsPath ./bump.json
    ./scripts/New-BumpDocs.ps1 -RecordsPath ./bump.json
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$RecordsPath,
    [string]$Path = '.',
    [string]$Date,
    [int]$MaxEntries = 24,
    [string]$RunUrl
)

$ErrorActionPreference = 'Stop'

$startMarker = '<!-- BUMP-LOG:START -->'
$endMarker   = '<!-- BUMP-LOG:END -->'

$languages = @(
    [ordered]@{
        Key         = 'pl'
        File        = 'docs/Dependencies/index.md'
        Title       = 'Aktualizacje zależności'
        Intro       = @(
            'Historia automatycznych aktualizacji referencji NuGet w bibliotekach tego repozytorium.',
            'Strona jest generowana przez workflow **Bump dependencies** (`.github/workflows/bump-deps.yml`)',
            'i dopisywana do każdego PR-a z podbiciem wersji paczek.'
        ) -join ' '
        NoteTitle   = 'Strona generowana automatycznie'
        NoteBody    = @(
            'Treść pomiędzy znacznikami `BUMP-LOG` jest nadpisywana przez `scripts/New-BumpDocs.ps1`.',
            'Nie edytuj jej ręcznie — zmiany zostaną utracone przy kolejnym przebiegu.'
        )
        Empty       = '_Brak zarejestrowanych aktualizacji._'
        Summary     = 'Zaktualizowano **{0}** {1} w **{2}** {3}.'
        RefWord     = @('referencję pakietu', 'referencje pakietów', 'referencji pakietów')
        ProjWord    = @('projekcie', 'projektach', 'projektach')
        RunLine     = 'Źródło: [przebieg workflow]({0}).'
        BumpHeader  = @('Pakiet', 'Z wersji', 'Na wersję', 'Licencja')
        SkipTitle   = '**Pominięte ({0}):**'
        SkipHeader  = @('Projekt', 'Pakiet', 'Kandydat', 'Powód')
    },
    [ordered]@{
        Key         = 'en'
        File        = 'docs-en/Dependencies/index.md'
        Title       = 'Dependency updates'
        Intro       = @(
            'History of automated NuGet reference updates across the libraries in this repository.',
            'This page is generated by the **Bump dependencies** workflow (`.github/workflows/bump-deps.yml`)',
            'and is part of every automated version-bump PR.'
        ) -join ' '
        NoteTitle   = 'Automatically generated page'
        NoteBody    = @(
            'Everything between the `BUMP-LOG` markers is rewritten by `scripts/New-BumpDocs.ps1`.',
            'Do not edit it by hand — your changes are lost on the next run.'
        )
        Empty       = '_No updates recorded yet._'
        Summary     = 'Updated **{0}** {1} across **{2}** {3}.'
        RefWord     = @('package reference', 'package references', 'package references')
        ProjWord    = @('project', 'projects', 'projects')
        RunLine     = 'Source: [workflow run]({0}).'
        BumpHeader  = @('Package', 'From', 'To', 'License')
        SkipTitle   = '**Skipped ({0}):**'
        SkipHeader  = @('Project', 'Package', 'Candidate', 'Reason')
    }
)

function Get-PluralForm {
    # Polish needs three forms (1 / 2-4 / 5+); English collapses to two.
    param([string[]]$Forms, [int]$Count)
    if ($Count -eq 1) { return $Forms[0] }
    $mod10 = $Count % 10
    $mod100 = $Count % 100
    if ($mod10 -ge 2 -and $mod10 -le 4 -and ($mod100 -lt 12 -or $mod100 -gt 14)) { return $Forms[1] }
    return $Forms[2]
}

function Format-Cell {
    param([string]$Value)
    if ([string]::IsNullOrWhiteSpace($Value)) { return '—' }
    return '`' + ($Value -replace '\|', '\|') + '`'
}

function New-PageTemplate {
    param($Lang)
    $lines = @(
        "# $($Lang.Title)",
        '',
        $Lang.Intro,
        '',
        "!!! info `"$($Lang.NoteTitle)`""
    )
    foreach ($b in $Lang.NoteBody) { $lines += "    $b" }
    $lines += @('', '---', '', $startMarker, $Lang.Empty, $endMarker, '')
    return ($lines -join "`n")
}

function New-EntryMarkdown {
    param($Lang, [string]$Heading, $Bumps, $Skips, [string]$RunUrl)

    $projects = @($Bumps | Select-Object -ExpandProperty projectPath -Unique)
    $lines = @("## $Heading", '')
    $lines += ($Lang.Summary -f
        $Bumps.Count,
        (Get-PluralForm -Forms $Lang.RefWord -Count $Bumps.Count),
        $projects.Count,
        (Get-PluralForm -Forms $Lang.ProjWord -Count $projects.Count))
    if ($RunUrl) {
        $lines += ''
        $lines += ($Lang.RunLine -f $RunUrl)
    }

    foreach ($project in ($projects | Sort-Object)) {
        $lines += ''
        $lines += "**$(Format-Cell $project)**"
        $lines += ''
        $lines += '| ' + ($Lang.BumpHeader -join ' | ') + ' |'
        $lines += '|' + ('---|' * $Lang.BumpHeader.Count)
        foreach ($b in ($Bumps | Where-Object { $_.projectPath -eq $project } | Sort-Object package)) {
            $lines += "| $(Format-Cell $b.package) | $(Format-Cell $b.from) | $(Format-Cell $b.to) | $(Format-Cell $b.license) |"
        }
    }

    if ($Skips -and $Skips.Count -gt 0) {
        $lines += ''
        $lines += ($Lang.SkipTitle -f $Skips.Count)
        $lines += ''
        $lines += '| ' + ($Lang.SkipHeader -join ' | ') + ' |'
        $lines += '|' + ('---|' * $Lang.SkipHeader.Count)
        foreach ($s in ($Skips | Sort-Object projectPath, package)) {
            $lines += "| $(Format-Cell $s.projectPath) | $(Format-Cell $s.package) | $(Format-Cell $s.to) | $($s.reason) |"
        }
    }

    $lines += ''
    return ($lines -join "`n")
}

if (-not (Test-Path -LiteralPath $RecordsPath)) {
    throw "Records file not found: $RecordsPath"
}

$report = [System.IO.File]::ReadAllText((Resolve-Path $RecordsPath).Path, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
$records = @($report.records)
$bumps = @($records | Where-Object { $_.action -eq 'bump' })
$skips = @($records | Where-Object { $_.action -eq 'skip' })

if ($bumps.Count -eq 0) {
    Write-Host 'No bumps recorded — documentation left untouched.' -ForegroundColor Gray
    return
}

if (-not $Date) {
    $generated = if ($report.generatedUtc) { [datetime]::Parse($report.generatedUtc).ToUniversalTime() }
                 else { (Get-Date).ToUniversalTime() }
    $Date = $generated.ToString('yyyy-MM-dd')
}

$root = (Resolve-Path $Path).Path
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

foreach ($lang in $languages) {
    $file = Join-Path $root $lang.File
    $dir = Split-Path -Parent $file
    if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }

    # Read through .NET so the encoding is UTF-8 on both PowerShell editions —
    # Windows PowerShell's Get-Content would decode the pages as ANSI and mangle them.
    if (Test-Path -LiteralPath $file) {
        $content = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8) -replace "`r`n", "`n"
    } else {
        $content = ''
    }
    if ($content -notmatch [regex]::Escape($startMarker) -or $content -notmatch [regex]::Escape($endMarker)) {
        $content = New-PageTemplate -Lang $lang
    }

    $startIdx = $content.IndexOf($startMarker)
    $endIdx = $content.IndexOf($endMarker)
    $head = $content.Substring(0, $startIdx + $startMarker.Length)
    $tail = $content.Substring($endIdx)
    $inner = $content.Substring($startIdx + $startMarker.Length, $endIdx - $startIdx - $startMarker.Length).Trim()
    if ($inner -eq $lang.Empty) { $inner = '' }

    # Keep same-day entries distinguishable when the workflow runs twice in a day.
    $heading = $Date
    $sameDay = ([regex]::Matches($inner, "(?m)^##\s+$([regex]::Escape($Date))\b")).Count
    if ($sameDay -gt 0) { $heading = "$Date ($($sameDay + 1))" }

    $existing = @()
    if ($inner) {
        $existing = @([regex]::Split($inner, '(?m)^(?=##\s)') | Where-Object { $_.Trim() })
    }

    $entry = New-EntryMarkdown -Lang $lang -Heading $heading -Bumps $bumps -Skips $skips -RunUrl $RunUrl
    $sections = @($entry) + $existing | Select-Object -First $MaxEntries
    $body = ($sections | ForEach-Object { $_.Trim() }) -join "`n`n"

    $new = "$head`n`n$body`n`n$tail".TrimEnd() + "`n"
    [System.IO.File]::WriteAllText($file, $new, $utf8NoBom)
    Write-Host "Updated $($lang.File) — entry '$heading' ($($bumps.Count) bumps, $($skips.Count) skips)" -ForegroundColor Green
}
